gcloud:
    project_id: "narratron"

agent:
    model_id: "gemini-3.1-flash-live-preview"
    compaction:
        trigger_tokens: 20000
        target_tokens: 10000

image_generation:
    reference_library_folder: "reference_library"
    cooldown_duration: 45

music:
    playlists_folder: "playlists"

orator:
    hotkey: "<ctrl>+<shift>+["
    server_url: "http://127.0.0.1:8000/api/orator/toggle_mic"
