gcloud:
    project_id: "narratron"

agent:
    model_id: "gemini-3.1-flash-live-preview"
    proactivity: false
    affective_dialog: false
    compaction:
        trigger_tokens: 20000
        target_tokens: 8000

image_generation:
    reference_library_folder: "reference_library"
    cooldown_duration: 12
    simple_model: "gemini-3.1-flash-lite-image"
    reference_model: "gemini-3.1-flash-lite-image"

music:
    playlists_folder: "playlists"
    cooldown_duration: 15

notes:
    cooldown_duration: 5

chat:
    cooldown_duration: 15

orator:
    hotkey: "<ctrl>+<shift>+["
    server_url: "http://127.0.0.1:8000/api/orator/toggle_mic"

email:
    enabled: false

smtp:
    from_email: "noreply@narratron.io"
    host: "smtp.gmail.com"
    port: 587


