from __future__ import annotations

import glob
import io
import asyncio
import logging
import os
from pathlib import Path
import re
import shutil
import time
from typing import Any, Dict, List, Optional, Tuple
from fastapi import WebSocket

from components.chat_manager import ChatManager
from components.scene_speech import SceneSpeechDispatcher, speaker_key
from providers.speech_provider import SpeechProvider
from utils.image_utils import extract_image_prompt
from components.theater_manager import TheaterManager

logger = logging.getLogger(__name__)

MAX_AGENT_THOUGHT_LENGTH = 360

class CanvasStateManager:
    """Encapsulates state for the web canvas UI including music playback, shown images,
    chat manager history, WebSocket connections, and doodle drawings.
    """
    def __init__(self, theater_id: str, theater_manager: TheaterManager):
        self.theater_id = theater_id
        self.theater_manager = theater_manager
        self.theater = theater_manager.theater(theater_id)
        chat_output_dir = str(self.theater.output_dir() / "chats")
        self.chat_manager = ChatManager(output_dir=chat_output_dir)
        self.current_image_basename: Optional[str] = None  
        
        # Shared state for music
        self.current_music_id: Optional[str] = None
        self.current_playlist: Optional[str] = None
        self.current_playlist_tracks: List[str] = []
        self.music_paused: bool = False
        self.current_playlist_time: float = 0.0
        
        # Shared state for shown image
        self.shown_image_path: Optional[str] = None
        self.shown_image_time: float = 0.0
        self.shown_image_prompt: str = ""
        self.shown_images_history: List[str] = []
        self.shown_image_transition: str = "crossfade"
        self.shown_image_effect: str = "gleam3"
        self.shown_animation_frames: List[str] = []
        # Changes only when the displayed image/presentation changes. This lets
        # long-running tools avoid replacing a newer image chosen meanwhile.
        self.image_revision: int = 0
        
        # WebSocket and doodles
        self.active_ws_connections: List[WebSocket] = []
        # Separate from the doodle socket: this carries notification-only
        # invalidations, while REST remains authoritative state.
        self.active_state_ws_connections: List[WebSocket] = []
        self._state_ws_loop: Optional[asyncio.AbstractEventLoop] = None
        self.state_revision: int = 0
        self.doodles_state: List[Dict[str, Any]] = []
        self.doodles_enabled: bool = True
        # Delivery ids are intentionally transient. They make a client retry
        # idempotent while this server process is alive without persisting
        # protocol bookkeeping into theater exports.
        self._processed_doodle_message_ids: set[str] = set()

        # Viewer collaboration mode — when enabled, the top audience suggestion
        # is fed to the Narratron agent on each observability cycle.
        self.viewer_collab_enabled: bool = False
        # Named elements & characters context
        # Story planning state context (named elements, characters, script)
        self.named_elements: List[Dict[str, str]] = []
        self.story_planning_state: Dict[str, Any] = {}
        # Authoritative dialogue generated by the story planner for display on
        # top of the current scene image.
        self.scene_dialogue: List[Dict[str, str]] = []
        self.narration: str = ""
        # A2UI protocol messages plus host-owned normalized canvas placement.
        self.interactive_surfaces: Dict[str, Dict[str, Any]] = {}
        # Normalized speaker name -> assigned Seed voice.  This is persisted
        # alongside the canvas so returning theaters keep their cast voices.
        self.character_voice_assignments: Dict[str, str] = {}
        self._scene_speech: Optional[SceneSpeechDispatcher] = None

        # Transient agent tool activity. This is intentionally not persisted: a
        # reconnect should not show an activity indicator left over from a
        # previous server process.
        self.image_generation_active: bool = False
        self.live_connection_active: bool = False
        self.live_connection_until: float = 0.0
        self.dice_roll_until: float = 0.0
        self.dice_roll_result: Optional[Dict[str, Any]] = None

        # The agent's latest chat-tool update is kept separately from the
        # public chat transcript. It is intentionally transient so a restarted
        # theater does not present an outdated status as current.
        self.current_agent_thought: str = ""
        self.current_agent_thought_time: float = 0.0

        self.load_state_from_disk()
        self._initialize_starting_image()

    def _initialize_starting_image(self) -> None:
        """Seed an otherwise blank canvas from its theater configuration."""
        if self.shown_image_path or self._has_generated_image():
            return

        # Import lazily to avoid a module cycle with TheaterManager.
        from utils.config_loader import get_theater_config

        config = get_theater_config(self.theater_id, base_dir=self.theater_manager.base_dir)
        starting_image = config.get("starting_image", "")
        if not isinstance(starting_image, str) or not starting_image.strip():
            return

        image_path = self._find_starting_reference(starting_image.strip())
        if not image_path:
            logger.warning(
                "Configured starting image '%s' was not found for theater '%s'.",
                starting_image,
                self.theater_id,
            )
            return

        self.update_shown_image(str(image_path), transition="crossfade", effect="gleam3")

    def _has_generated_image(self) -> bool:
        image_dir = self.theater.image_artifacts_dir()
        if not image_dir.exists():
            return False
        return any(path.is_file() and path.suffix.lower() in {".png", ".jpg", ".jpeg", ".webp"} for path in image_dir.rglob("*"))

    def _find_starting_reference(self, image_name: str) -> Optional[Path]:
        reference_dir = self.theater.references_dir()
        if not reference_dir.exists():
            return None

        normalized_name = re.sub(r"[^a-zA-Z0-9_-]", "_", image_name).lower()
        for image_path in reference_dir.rglob("*"):
            if not image_path.is_file() or image_path.suffix.lower() not in {".png", ".jpg", ".jpeg", ".webp"}:
                continue
            normalized_stem = re.sub(r"[^a-zA-Z0-9_-]", "_", image_path.stem).lower()
            if image_name.lower() in {image_path.name.lower(), image_path.stem.lower()} or normalized_name == normalized_stem:
                return image_path
        return None

    def load_state_from_disk(self):
        """Restore canvas state from local theater.json if available."""
        import json
        sess_dir = self.theater.directory()
        theater_file = sess_dir / "theater.json"
        legacy_state_file = sess_dir / "theater_state.json"
        
        target_file = theater_file if theater_file.exists() else (legacy_state_file if legacy_state_file.exists() else None)
        
        if target_file:
            try:
                with open(target_file, "r", encoding="utf-8") as f:
                    data = json.load(f)
                    c_state = data.get("canvas_state") or data
                    self.current_image_basename = c_state.get("current_image_basename")
                    self.shown_image_path = c_state.get("shown_image_path")
                    self.shown_image_prompt = c_state.get("shown_image_prompt", "")
                    self.shown_images_history = c_state.get("shown_images_history", [])
                    self.shown_image_transition = c_state.get("shown_image_transition", "fade")
                    self.shown_image_effect = c_state.get("shown_image_effect", "gleam3")
                    self.shown_animation_frames = c_state.get("shown_animation_frames", [])
                    self.current_playlist = c_state.get("current_playlist")
                    self.current_playlist_tracks = c_state.get("current_playlist_tracks", [])
                    self.music_paused = c_state.get("music_paused", False)
                    self.doodles_state = c_state.get("doodles", [])
                    self.doodles_enabled = c_state.get("doodles_enabled", True)
                    self.viewer_collab_enabled = c_state.get("viewer_collab_enabled", False)
                    self.named_elements = c_state.get("named_elements", [])
                    self.story_planning_state = c_state.get("story_planning_state", {})
                    self.scene_dialogue = c_state.get("scene_dialogue", [])
                    self.narration = str(c_state.get("narration") or "")
                    surfaces = c_state.get("interactive_surfaces", [])
                    self.interactive_surfaces = {
                        str(item.get("surface_id")): dict(item)
                        for item in surfaces
                        if isinstance(item, dict) and item.get("surface_id")
                    } if isinstance(surfaces, list) else {}
                    assignments = c_state.get("character_voice_assignments", {})
                    self.character_voice_assignments = {
                        str(key): str(value) for key, value in assignments.items()
                    } if isinstance(assignments, dict) else {}
                    chat_msgs = c_state.get("chat_messages", [])
                    if chat_msgs:
                        self.chat_manager.messages = chat_msgs
                    self.chat_manager.load_suggestions(c_state.get("suggestions", []))
                    logger.info(f"Loaded canvas state from {target_file.name} for theater '{self.theater_id}'.")
            except Exception as e:
                logger.warning(f"Failed to load canvas state for {self.theater_id}: {e}")

    def get_sticky_notes(self) -> List[Dict[str, str]]:
        if "sticky_notes" in self.story_planning_state:
            return list(self.story_planning_state.get("sticky_notes", []))
        if "named_elements" in self.story_planning_state:
            return [
                {
                    "topic": elem.get("topic", elem.get("name", "")),
                    "info": elem.get("info", elem.get("content", "")),
                    "name": elem.get("topic", elem.get("name", "")),
                    "content": elem.get("info", elem.get("content", "")),
                }
                for elem in self.story_planning_state.get("named_elements", [])
            ]
        return list(self.named_elements)

    def set_sticky_notes(self, notes: List[Dict[str, str]]):
        self.named_elements = list(notes or [])
        if isinstance(self.story_planning_state, dict):
            self.story_planning_state["sticky_notes"] = list(notes or [])
            self.story_planning_state["named_elements"] = list(notes or [])
        sess_dir = self.theater.directory()
        if sess_dir.exists():
            self.export_theater_data(theater_dir=sess_dir)
        self._notify_state_changed("latest")

    def get_named_elements(self) -> List[Dict[str, str]]:
        return self.get_sticky_notes()

    def set_named_elements(self, elements: List[Dict[str, str]]):
        self.set_sticky_notes(elements)

    def get_story_planning_state(self) -> Dict[str, Any]:
        return dict(self.story_planning_state) if isinstance(self.story_planning_state, dict) else {}

    def set_story_planning_state(self, state: Dict[str, Any]):
        self.story_planning_state = dict(state) if isinstance(state, dict) else {}
        if "sticky_notes" in self.story_planning_state:
            self.named_elements = list(self.story_planning_state["sticky_notes"])
        elif "named_elements" in self.story_planning_state:
            self.named_elements = list(self.story_planning_state["named_elements"])
        sess_dir = self.theater.directory()
        if sess_dir.exists():
            self.export_theater_data(theater_dir=sess_dir)
        self._notify_state_changed("latest")

    def set_scene_dialogue(self, dialogue: List[Dict[str, str]]):
        """Set the planner-authored speech/thought bubbles shown on the canvas."""
        self.scene_dialogue = [dict(item) for item in (dialogue or []) if isinstance(item, dict)][:3]
        sess_dir = self.theater.directory()
        if sess_dir.exists():
            self.export_theater_data(theater_dir=sess_dir)
        self._notify_state_changed("latest")
        if self._scene_speech:
            self._scene_speech.dispatch(self.scene_dialogue)

    def get_character_voice(self, speaker: str) -> Optional[str]:
        """Get assigned voice for a character, if any."""
        return self.character_voice_assignments.get(speaker_key(speaker))

    def assign_character_voice(self, speaker: str, voice: str) -> None:
        """Assign a specific voice to a character in canvas state."""
        self.character_voice_assignments[speaker_key(speaker)] = str(voice)
        self._persist_voice_assignments()

    def get_character_voice_tags(self, speaker: str) -> list[str]:
        """Find character voice tags in story planning state."""
        normalized = speaker.strip().lower()
        characters = self.story_planning_state.get("characters", [])
        if isinstance(characters, list):
            for char in characters:
                if isinstance(char, dict) and str(char.get("name", "")).strip().lower() == normalized:
                    tags = char.get("voice_tags", [])
                    if isinstance(tags, (list, tuple, set)):
                        return [str(t).strip().lower() for t in tags if str(t).strip().lower() in ("male", "female")]
                    if isinstance(tags, str) and tags.strip().lower() in ("male", "female"):
                        return [tags.strip().lower()]
        return []

    def get_character_description(self, speaker: str) -> str:
        """Find character metadata in story planning state or named elements / sticky notes."""
        normalized = speaker.strip().lower()
        characters = self.story_planning_state.get("characters", [])
        if isinstance(characters, list):
            for char in characters:
                if isinstance(char, dict) and str(char.get("name", "")).strip().lower() == normalized:
                    desc_parts = [
                        char.get("name", ""),
                        char.get("description", ""),
                        char.get("personality", ""),
                        char.get("motivation", ""),
                        char.get("quirk", ""),
                    ]
                    return " ".join(str(p) for p in desc_parts if p).strip()
        for elem in self.get_sticky_notes():
            if isinstance(elem, dict):
                key = str(elem.get("topic") or elem.get("name") or "").strip().lower()
                if key == normalized:
                    content = elem.get("info") or elem.get("content") or elem.get("description") or ""
                    return f"{elem.get('topic') or elem.get('name', '')} {content}".strip()
        return speaker

    def enable_scene_speech(self, provider: SpeechProvider | None = None) -> None:
        """Start automatic Seed Speech delivery; no theater configuration needed."""
        if self._scene_speech is None:
            if provider is None:
                from providers import get_speech_provider, SpeechProviderError
                try:
                    provider = get_speech_provider("fal-seed-speech")
                except SpeechProviderError:
                    from providers.fal_seed_speech_provider import FalSeedSpeechProvider
                    provider = FalSeedSpeechProvider()
            self._scene_speech = SceneSpeechDispatcher(
                theater_id=self.theater_id,
                output_dir=self.theater.output_dir(),
                assignments=self.character_voice_assignments,
                persist_assignments=self._persist_voice_assignments,
                publish_audio=self._publish_scene_audio,
                provider=provider,
                character_lookup=self.get_character_voice_tags,
            )

    def _persist_voice_assignments(self) -> None:
        sess_dir = self.theater.directory()
        self.export_theater_data(theater_dir=sess_dir)

    def _publish_scene_audio(self, message: Dict[str, Any]) -> None:
        if not self.active_state_ws_connections or not self._state_ws_loop or self._state_ws_loop.is_closed():
            return
        try:
            asyncio.run_coroutine_threadsafe(self.broadcast_state_ws_message(message), self._state_ws_loop)
        except RuntimeError:
            pass

    def set_narration(self, narration: str):
        """Set the planner-authored narration shown in white italics."""
        self.narration = " ".join(str(narration or "").strip().split()[:45])[:500]
        sess_dir = self.theater.directory()
        if sess_dir.exists():
            self.export_theater_data(theater_dir=sess_dir)
        self._notify_state_changed("latest")

    def upsert_interactive_surface(self, surface: Dict[str, Any], max_surfaces: int = 5) -> None:
        """Store one generated A2UI surface and notify connected renderers."""
        surface_id = str(surface.get("surface_id") or "")
        if not surface_id:
            raise ValueError("Interactive surface requires a surface_id.")
        self.interactive_surfaces[surface_id] = dict(surface)
        while len(self.interactive_surfaces) > max(1, max_surfaces):
            self.interactive_surfaces.pop(next(iter(self.interactive_surfaces)))
        sess_dir = self.theater.directory()
        if sess_dir.exists():
            self.export_theater_data(theater_dir=sess_dir)
        self._notify_state_changed("latest")

    def delete_interactive_surface(self, surface_id: str = "all") -> int:
        """Remove a single A2UI surface or every current surface."""
        if surface_id == "all":
            removed = len(self.interactive_surfaces)
            self.interactive_surfaces.clear()
        else:
            removed = int(self.interactive_surfaces.pop(str(surface_id), None) is not None)
        if removed:
            sess_dir = self.theater.directory()
            if sess_dir.exists():
                self.export_theater_data(theater_dir=sess_dir)
            self._notify_state_changed("latest")
        return removed

    def move_interactive_surface(
        self, surface_id: str, left_pct: float, top_pct: float
    ) -> Optional[Dict[str, float]]:
        """Persist a user-selected canvas position for an A2UI surface."""
        surface = self.interactive_surfaces.get(str(surface_id))
        if not surface:
            return None
        placement = surface.setdefault("placement", {})
        placement["left_pct"] = round(max(2.0, min(98.0, float(left_pct))), 2)
        placement["top_pct"] = round(max(2.0, min(98.0, float(top_pct))), 2)
        sess_dir = self.theater.directory()
        if sess_dir.exists():
            self.export_theater_data(theater_dir=sess_dir)
        self._notify_state_changed("latest")
        return {"left_pct": placement["left_pct"], "top_pct": placement["top_pct"]}

    def get_interactive_action(self, surface_id: str, component_id: str, action_name: str) -> Optional[Dict[str, Any]]:
        """Resolve an action against the authoritative generated component tree."""
        surface = self.interactive_surfaces.get(str(surface_id))
        components: Dict[str, Dict[str, Any]] = {}
        for message in (surface or {}).get("messages", []):
            if not isinstance(message, dict):
                continue
            payload = message.get("createSurface") or message.get("updateComponents") or {}
            for component in payload.get("components", []):
                if isinstance(component, dict) and component.get("id"):
                    components[str(component["id"])] = component
        component = components.get(str(component_id), {})
        event = (component.get("action") or {}).get("event", {})
        if event.get("name") == action_name:
            return dict(event)
        return None


    def _notify_state_changed(self, *domains: str):
        """Schedule a compact state invalidation for connected viewers."""
        self.state_revision += 1
        if not self.active_state_ws_connections or not self._state_ws_loop:
            return
        payload = {
            "type": "state_changed",
            "revision": self.state_revision,
            "domains": sorted(set(domains)),
        }
        try:
            try:
                running_loop = asyncio.get_running_loop()
            except RuntimeError:
                running_loop = None
            if running_loop is self._state_ws_loop:
                running_loop.create_task(self.broadcast_state_ws_message(payload))
            else:
                if self._state_ws_loop.is_closed():
                    return
                asyncio.run_coroutine_threadsafe(
                    self.broadcast_state_ws_message(payload), self._state_ws_loop
                )
        except RuntimeError:
            # The loop may be gone during application shutdown. Reconnection
            # sends state_ready and the browser performs a full refresh.
            pass

    def update_current_music(self, music_id: str, tracks: List[str]):
        self.current_music_id = music_id
        self.current_playlist = music_id
        self.current_playlist_tracks = tracks
        self.music_paused = False
        self.current_playlist_time = time.time()
        self._notify_state_changed("latest")

    def pause_current_music(self):
        self.music_paused = True
        self.current_playlist_time = time.time()
        self._notify_state_changed("latest")

    def resume_current_music(self):
        self.music_paused = False
        self.current_playlist_time = time.time()
        self._notify_state_changed("latest")

    def _get_url_for_path(self, file_path: str) -> str:
        if not file_path:
            return ""
        sel_path_obj = Path(file_path).resolve()
        if "references" in sel_path_obj.parts or "reference_library" in sel_path_obj.parts:
            return f"/theaters/{self.theater_id}/references/{sel_path_obj.name}"
        try:
            relative_path = sel_path_obj.relative_to(self.theater.output_dir().resolve()).as_posix()
        except ValueError:
            relative_path = sel_path_obj.name
        return f"/theaters/{self.theater_id}/output/{relative_path}"

    def update_shown_image(
        self,
        file_path: str,
        theater_id: Optional[str] = None,
        transition: str = "crossfade",
        effect: str = "gleam3",
        clear_animation: bool = True,
    ):
        transition = transition or "crossfade"
        effect = effect or "gleam3"
        image_changed = file_path != self.shown_image_path
        presentation_changed = (
            image_changed
            or transition != getattr(self, "shown_image_transition", "crossfade")
            or effect != getattr(self, "shown_image_effect", "gleam3")
        )
        if image_changed:
            self.doodles_state.clear()
            # Interactables are composed against a specific visual scene.
            # Keep explicit HUD/tracker surfaces but discard scene-bound UI.
            self.interactive_surfaces = {
                surface_id: surface
                for surface_id, surface in self.interactive_surfaces.items()
                if bool(surface.get("persistent", False))
            }
        if presentation_changed:
            self.shown_image_time = time.time()
        elif not getattr(self, "shown_image_time", None):
            self.shown_image_time = time.time()
        self.shown_image_path = file_path
        self.shown_image_prompt = extract_image_prompt(file_path)
        self.shown_image_transition = transition
        self.shown_image_effect = effect
        if clear_animation:
            self.shown_animation_frames = []
        if presentation_changed:
            self.image_revision += 1
        self._notify_state_changed("latest")

        if file_path:
            image_url = self._get_url_for_path(file_path)
            history_item = {
                "path": file_path,
                "url": image_url,
                "prompt": self.shown_image_prompt,
                "time": self.shown_image_time,
                "transition": self.shown_image_transition,
                "effect": self.shown_image_effect,
            }
            # Append if history is empty or last item path differs from file_path
            last_path = None
            if self.shown_images_history:
                last_entry = self.shown_images_history[-1]
                last_path = last_entry.get("path") if isinstance(last_entry, dict) else last_entry
            if last_path != file_path:
                self.shown_images_history.append(history_item)
                if len(self.shown_images_history) > 100:
                    self.shown_images_history = self.shown_images_history[-100:]
            elif self.shown_images_history:
                self.shown_images_history[-1] = history_item

        # Automatically copy shown image into theater output directory if outside theater output dir
        target_theater = theater_id or self.theater_id
        if target_theater and file_path and os.path.exists(file_path):
            sess_out_dir = self.theater_manager.theater(target_theater).output_dir()
            sess_out_dir.mkdir(parents=True, exist_ok=True)
            file_path_obj = Path(file_path).resolve()
            try:
                # Check if file is already inside sess_out_dir
                file_path_obj.relative_to(sess_out_dir)
            except ValueError:
                # File is outside theater output directory: copy to theater output dir
                target_path = sess_out_dir / os.path.basename(file_path)
                if not target_path.exists():
                    try:
                        shutil.copy2(file_path, target_path)
                    except Exception as e:
                        logger.warning(f"Failed to copy shown image to theater output dir: {e}")

    def show_triframe(self, frame_paths: List[str], theater_id: Optional[str] = None) -> None:
        """Display a generated three-frame sequence as a looping canvas animation."""
        if len(frame_paths) != 3 or any(not path for path in frame_paths):
            raise ValueError("A tri-frame animation requires exactly three image paths.")
        self.update_shown_image(
            frame_paths[0],
            theater_id=theater_id,
            transition="crossfade",
            effect="none",
            clear_animation=False,
        )
        self.shown_animation_frames = list(frame_paths)
        self._notify_state_changed("latest")

    def add_chat_message(self, text: str, author: str = "agent", profile_username: Optional[str] = None, profile_color: Optional[str] = None):
        message = {"author": author, "text": text}
        if profile_username:
            message["profile_username"] = profile_username
        if profile_color:
            message["profile_color"] = profile_color
        self.chat_manager.add_message(message)
        self._notify_state_changed("chat")

    def consume_top_suggestion(self) -> Optional[Dict[str, Any]]:
        suggestion = self.chat_manager.consume_top_suggestion()
        if suggestion:
            self._notify_state_changed("chat", "suggestions")
        return suggestion

    def set_agent_thought(self, text: str):
        normalized_text = text.strip()
        if len(normalized_text) > MAX_AGENT_THOUGHT_LENGTH:
            normalized_text = normalized_text[: MAX_AGENT_THOUGHT_LENGTH - 1].rstrip() + "…"
        self.current_agent_thought = normalized_text
        self.current_agent_thought_time = time.time() if self.current_agent_thought else 0.0
        self._notify_state_changed("latest")

    def get_agent_thought(self) -> Dict[str, Any]:
        return {
            "text": self.current_agent_thought,
            "time": self.current_agent_thought_time,
        }

    def register_websocket(self, websocket: WebSocket, user: Optional[Dict[str, Any]] = None):
        if websocket not in self.active_ws_connections:
            self.active_ws_connections.append(websocket)
        if not hasattr(self, "active_user_connections"):
            self.active_user_connections = {}
        self.active_user_connections[websocket] = user

    def unregister_websocket(self, websocket: WebSocket):
        if websocket in self.active_ws_connections:
            self.active_ws_connections.remove(websocket)
        if hasattr(self, "active_user_connections") and websocket in self.active_user_connections:
            del self.active_user_connections[websocket]

    def register_state_websocket(self, websocket: WebSocket):
        if websocket not in self.active_state_ws_connections:
            self.active_state_ws_connections.append(websocket)
        self._state_ws_loop = asyncio.get_running_loop()

    def unregister_state_websocket(self, websocket: WebSocket):
        if websocket in self.active_state_ws_connections:
            self.active_state_ws_connections.remove(websocket)

    async def broadcast_state_ws_message(self, message: Dict[str, Any]):
        for connection in list(self.active_state_ws_connections):
            try:
                await connection.send_json(message)
            except Exception:
                self.unregister_state_websocket(connection)

    def get_active_viewers(self) -> List[Dict[str, Any]]:
        """Return list of distinct authenticated users currently connected as active canvas viewers."""
        if not hasattr(self, "active_user_connections"):
            return []
        users_by_id = {}
        for u in self.active_user_connections.values():
            if u and "id" in u:
                users_by_id[u["id"]] = {"id": u["id"], "username": u.get("username", "")}
        return list(users_by_id.values())


    async def broadcast_ws_message(self, message: Dict[str, Any], sender: Optional[WebSocket] = None):
        for connection in list(self.active_ws_connections):
            if connection != sender:
                try:
                    await connection.send_json(message)
                except Exception:
                    pass

    def add_doodle(self, doodle: Dict[str, Any]):
        self.add_doodles([doodle])

    def add_doodles(self, doodles: List[Dict[str, Any]]):
        """Store a group of doodles and persist it with one disk write.

        A browser sends several adjacent segments together, so persisting them
        together also avoids rewriting theater.json for every pointer event.
        """
        if any(doodle.get("type") == "clear" for doodle in doodles):
            self.doodles_state.clear()
        else:
            self.doodles_state.extend(doodles)
        sess_dir = self.theater.directory()
        sess_dir.mkdir(parents=True, exist_ok=True)
        self.export_theater_data(theater_dir=sess_dir)

    def get_doodle_snapshot_batches(self) -> List[Dict[str, Any]]:
        """Encode persisted segments into compact, style-grouped stroke paths."""
        batches: List[Dict[str, Any]] = []
        for action in self.doodles_state:
            if action.get("type") != "draw":
                continue
            try:
                x0, y0 = action["x0"], action["y0"]
                x1, y1 = action["x1"], action["y1"]
            except KeyError:
                continue
            color = action.get("color")
            size = action.get("size", 3)
            if (batches and batches[-1]["color"] == color and batches[-1]["size"] == size
                    and batches[-1]["points"][-2:] == [x0, y0]):
                batches[-1]["points"].extend([x1, y1])
            else:
                batches.append({"color": color, "size": size, "points": [x0, y0, x1, y1]})
        return batches

    def set_doodles_enabled(self, enabled: bool):
        self.doodles_enabled = bool(enabled)
        sess_dir = self.theater.directory()
        if sess_dir.exists():
            self.export_theater_data(theater_dir=sess_dir)

    def set_viewer_collab_enabled(self, enabled: bool):
        """Toggle viewer collaboration mode on or off."""
        self.viewer_collab_enabled = bool(enabled)
        sess_dir = self.theater.directory()
        if sess_dir.exists():
            self.export_theater_data(theater_dir=sess_dir)
        self._notify_state_changed("latest")

    def get_doodle_snapshot_data(self) -> List[Dict[str, Any]]:
        """Return the current doodle stroke data for agent observability."""
        return list(self.doodles_state)

    def get_doodle_snapshot_png(self) -> Optional[bytes]:
        """Render the current image with normalized doodle strokes as a PNG."""
        if not self.shown_image_path or not self.doodles_state:
            return None
        try:
            from PIL import Image, ImageDraw

            with Image.open(self.shown_image_path) as source:
                image = source.convert("RGBA")
            image.thumbnail((1600, 1600))
            draw = ImageDraw.Draw(image)
            width, height = image.size
            scale = max(1.0, min(width, height) / 900)
            for action in self.doodles_state:
                if action.get("type") != "draw":
                    continue
                try:
                    points = (float(action["x0"]) * width, float(action["y0"]) * height,
                              float(action["x1"]) * width, float(action["y1"]) * height)
                    draw.line(points, fill=action.get("color", "#ffffff"),
                              width=max(1, round(float(action.get("size", 3)) * scale)))
                except (KeyError, TypeError, ValueError):
                    continue
            output = io.BytesIO()
            # This image is an ephemeral agent-observability payload. Favor
            # quick encoding over expensive PNG optimization.
            image.convert("RGB").save(output, format="PNG", compress_level=1)
            return output.getvalue()
        except Exception as exc:
            logger.warning("Failed to render viewer doodle snapshot: %s", exc)
            return None

    def set_tool_activity(
        self, tool: str, active: bool = True, recent_seconds: float = 5.0,
        result: Optional[Dict[str, Any]] = None,
    ):
        """Update transient canvas indicators for agent tool use."""
        if tool == "image":
            self.image_generation_active = bool(active)
        elif tool == "live":
            self.live_connection_active = bool(active)
            if active and recent_seconds > 0:
                self.live_connection_until = time.time() + max(0.0, recent_seconds)
            elif not active:
                self.live_connection_until = 0.0
        elif tool == "dice":
            self.dice_roll_until = (
                time.time() + max(0.0, recent_seconds)
                if active and recent_seconds > 0
                else 0.0
            )
            self.dice_roll_result = dict(result) if active and result else None
        self._notify_state_changed("latest")

    def get_tool_activity(self) -> Dict[str, bool]:
        now = time.time()
        dice_rolling = now < self.dice_roll_until
        return {
            "image_generating": self.image_generation_active,
            "live_ready": self.live_connection_active or (now < self.live_connection_until),
            "dice_rolling": dice_rolling,
            "dice_result": self.dice_roll_result if dice_rolling else None,
        }

    def _get_music_state(self) -> Dict[str, Any]:
        """Return the current music playback state payload."""
        playlist_id = self.current_music_id or getattr(self, "current_playlist", None)
        return {
            "music_id": playlist_id,
            "playlist": playlist_id,
            "tracks": self.current_playlist_tracks,
            "paused": self.music_paused,
            "time": self.current_playlist_time,
        }

    def _resolve_adventure_cover(self) -> Optional[Tuple[Path, str]]:
        """Look up adventure cover image from metadata.json if present."""
        if not self.theater_id:
            return None
        theater_dir = self.theater.directory()
        theater_ref_dir = self.theater.references_dir()
        metadata_file = theater_dir / "metadata.json"
        if not metadata_file.exists():
            return None

        try:
            import json
            meta = json.loads(metadata_file.read_text(encoding="utf-8"))
        except Exception as e:
            logger.warning(f"Failed to read metadata.json for theater {self.theater_id}: {e}")
            return None

        cover_image_setting = meta.get("cover_image")
        cover_file = None
        if cover_image_setting:
            clean_cover = cover_image_setting
            for prefix in ("references/", "reference_library/"):
                if clean_cover.startswith(prefix):
                    clean_cover = clean_cover[len(prefix):]

            candidates = [
                theater_ref_dir / cover_image_setting,
                theater_dir / cover_image_setting,
                theater_ref_dir / clean_cover,
                theater_dir / clean_cover,
                theater_ref_dir / Path(cover_image_setting).name,
            ]
            for cand in candidates:
                if cand.exists() and cand.is_file():
                    cover_file = cand
                    break

            if not cover_file and theater_ref_dir.exists():
                match_name = Path(cover_image_setting).name.lower()
                for f in theater_ref_dir.rglob("*"):
                    if f.is_file() and f.name.lower() == match_name:
                        cover_file = f
                        break

        if cover_file:
            title = meta.get("title")
            prompt = extract_image_prompt(str(cover_file)) or (f"Adventure Cover: {title}" if title else f"Mounted Reference: {cover_file.stem}")
            return cover_file, prompt
        return None

    def _resolve_reference_fallback(self) -> Optional[Tuple[Path, str]]:
        """Fallback to first reference image (prioritizing cover-named images)."""
        if not self.theater_id:
            return None
        theater_ref_dir = self.theater.references_dir()
        if not theater_ref_dir.exists():
            return None
        ref_images = [f for f in theater_ref_dir.iterdir() if f.is_file() and f.suffix.lower() in (".png", ".jpg", ".jpeg", ".webp")]
        if not ref_images:
            return None
        cover_candidates = [f for f in ref_images if "cover" in f.stem.lower()]
        chosen = cover_candidates[0] if cover_candidates else ref_images[0]
        prompt = extract_image_prompt(str(chosen)) or f"Mounted Reference: {chosen.stem}"
        return chosen, prompt

    def _resolve_active_image(self) -> Tuple[Optional[str], Optional[str], float, str]:
        """Resolve current displayed image: explicit shown image, newest artifact, adventure cover, or mounted reference.

        Returns:
            Tuple of (image_url, file_path_str, timestamp, prompt_text)
        """
        # 1. Explicit shown image
        if self.shown_image_path:
            return self._get_url_for_path(self.shown_image_path), self.shown_image_path, self.shown_image_time, self.shown_image_prompt

        # 2. Output directory latest generated image
        image_folder = str(self.theater.output_dir())
        if os.path.exists(image_folder):
            files = []
            for ext in ("*.png", "*.jpg", "*.jpeg", "*.webp"):
                files.extend(glob.glob(os.path.join(image_folder, ext)))
            if files:
                newest = max(files, key=os.path.getmtime)
                return self._get_url_for_path(newest), newest, os.path.getmtime(newest), extract_image_prompt(newest)

        # 3. Adventure cover from metadata.json
        cover = self._resolve_adventure_cover()
        if cover:
            cover_path, prompt = cover
            return self._get_url_for_path(str(cover_path)), str(cover_path), 0.0, prompt

        # 4. Mounted reference fallback
        ref = self._resolve_reference_fallback()
        if ref:
            ref_path, prompt = ref
            return self._get_url_for_path(str(ref_path)), str(ref_path), 0.0, prompt

        return None, None, 0.0, ""

    def get_latest_state(self) -> Dict[str, Any]:
        music_state = self._get_music_state()
        image_url, selected_file, selected_time, prompt_text = self._resolve_active_image()

        if selected_file:
            self.current_image_basename = os.path.basename(selected_file)

        transition = getattr(self, "shown_image_transition", "fade") or "fade"
        effect = getattr(self, "shown_image_effect", "gleam3") or "gleam3"

        formatted_history = []
        for h in self.shown_images_history:
            if isinstance(h, dict):
                formatted_history.append(h)
            elif isinstance(h, str):
                formatted_history.append({
                    "path": h,
                    "url": self._get_url_for_path(h),
                    "prompt": extract_image_prompt(h),
                    "time": 0.0,
                    "transition": transition,
                    "effect": effect,
                })

        if selected_file and not self.shown_images_history:
            item = {
                "path": selected_file,
                "url": image_url,
                "prompt": prompt_text,
                "time": selected_time,
                "transition": transition,
                "effect": effect,
            }
            self.shown_images_history.append(item)
            formatted_history.append(item)

        res = {
            "latest": image_url,
            "time": selected_time,
            "prompt": prompt_text,
            "music": music_state,
            "doodles_enabled": self.doodles_enabled,
            "viewer_collab_enabled": self.viewer_collab_enabled,
            "transition": transition,
            "effect": effect,
            "history": formatted_history,
            "tool_activity": self.get_tool_activity(),
            "agent_thought": self.get_agent_thought(),
            "scene_dialogue": list(self.scene_dialogue),
            "narration": self.narration,
            "character_voice_assignments": dict(self.character_voice_assignments),
            "sticky_notes": self.get_sticky_notes(),
            "interactive_surfaces": list(self.interactive_surfaces.values()),
        }
        if self.shown_animation_frames:
            res["animation"] = {
                "type": "triframe",
                "frames": [self._get_url_for_path(path) for path in self.shown_animation_frames],
                "frame_duration_ms": 1400,
                "crossfade_duration_ms": 500,
            }
        logger.debug(f"[/api/latest] returning latest={res['latest']}, time={res['time']}, history_len={len(formatted_history)}, playlist={music_state['playlist']}")
        return res

    def export_theater_data(self, theater_dir: Optional[Path] = None) -> tuple[Dict[str, Any], List[Dict[str, Any]]]:
        """Ensure current displayed image is saved and gather theater metadata, canvas data and files."""
        import json
        if self.shown_image_path and theater_dir:
            self.update_shown_image(
                self.shown_image_path,
                theater_id=theater_dir.name,
                transition=getattr(self, "shown_image_transition", "fade"),
                effect=getattr(self, "shown_image_effect", "gleam3"),
                clear_animation=False,
            )

        canvas_state = {
            "current_image_basename": self.current_image_basename,
            "shown_image_path": self.shown_image_path,
            "shown_image_prompt": self.shown_image_prompt,
            "shown_images_history": self.shown_images_history,
            "shown_image_transition": getattr(self, "shown_image_transition", "fade"),
            "shown_image_effect": getattr(self, "shown_image_effect", "gleam3"),
            "shown_animation_frames": list(self.shown_animation_frames),
            "current_playlist": self.current_playlist,
            "current_playlist_tracks": self.current_playlist_tracks,
            "music_paused": self.music_paused,
            "doodles": list(self.doodles_state),
            "doodles_enabled": self.doodles_enabled,
            "viewer_collab_enabled": self.viewer_collab_enabled,
            "named_elements": list(self.named_elements),
            "story_planning_state": dict(self.story_planning_state) if isinstance(self.story_planning_state, dict) else {},
            "scene_dialogue": list(self.scene_dialogue),
            "narration": self.narration,
            "interactive_surfaces": list(self.interactive_surfaces.values()),
            "character_voice_assignments": dict(self.character_voice_assignments),
            "suggestions": self.chat_manager.export_suggestions(),
            "chat_messages": self.chat_manager.get_messages(),
        }

        metadata = {}
        if theater_dir:
            theater_dir = Path(theater_dir).resolve()
            theater_dir.mkdir(parents=True, exist_ok=True)
            meta_file = theater_dir / "theater.json"
            if meta_file.exists():
                try:
                    with open(meta_file, "r", encoding="utf-8") as f:
                        metadata = json.load(f)
                except Exception:
                    metadata = {}

            # A canvas update can be the first write after a restored
            # deployment.  Always retain the minimum TheaterMetadata identity
            # fields so later agent initialization can read theater.json.
            metadata.setdefault("theater_id", self.theater_id)
            metadata.setdefault("name", self.theater_id)
            metadata["canvas_state"] = canvas_state

            try:
                with open(meta_file, "w", encoding="utf-8") as f:
                    json.dump(metadata, f, indent=2)
            except Exception as e:
                logger.warning(f"Failed to update theater.json: {e}")

            # Remove legacy theater_state.json if it exists
            legacy_file = theater_dir / "theater_state.json"
            if legacy_file.exists():
                try:
                    legacy_file.unlink()
                except Exception:
                    pass

        state_data = dict(metadata)
        if "canvas_state" not in state_data:
            state_data["canvas_state"] = canvas_state

        image_files = []
        seen_filenames = set()
        if theater_dir and theater_dir.exists():
            for f in theater_dir.rglob("*"):
                if f.is_file() and f.name not in ["theater.json", "theater_state.json"]:
                    rel_path = str(f.relative_to(theater_dir)).replace("\\", "/")
                    if rel_path not in seen_filenames:
                        seen_filenames.add(rel_path)
                        if "references" in f.parts:
                            category = "reference"
                        elif "output" in f.parts:
                            category = "output"
                        else:
                            category = str(f.parent.relative_to(theater_dir)).replace("\\", "/")

                        try:
                            with open(f, "rb") as fp:
                                image_files.append({
                                    "filename": f.name,
                                    "category": category,
                                    "data": fp.read()
                                })
                        except Exception:
                            pass

        return state_data, image_files
