-- Narratron PostgreSQL schema. Timestamps remain text intentionally: the
-- application already stores and compares ISO-8601 UTC values at its boundary.
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL,
    email TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    salt TEXT NOT NULL,
    credits DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    total_voice_minutes DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    total_images_created INTEGER NOT NULL DEFAULT 0,
    total_music_created INTEGER NOT NULL DEFAULT 0,
    total_story_plans INTEGER NOT NULL DEFAULT 0,
    total_character_voiced_turns INTEGER NOT NULL DEFAULT 0,
    total_interactive_canvas_used INTEGER NOT NULL DEFAULT 0,
    mic_sensitivity DOUBLE PRECISION NOT NULL DEFAULT 0.5,
    bio TEXT NOT NULL DEFAULT '',
    stats_visible BOOLEAN NOT NULL DEFAULT FALSE,
    lifetime_credits_used DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    profile_color TEXT NOT NULL DEFAULT '#818cf8',
    created_at TEXT NOT NULL,
    age_attested_at TEXT,
    age_attestation_version TEXT,
    last_active_at TEXT
);

CREATE UNIQUE INDEX IF NOT EXISTS users_username_lower_unique ON users (LOWER(username));
CREATE UNIQUE INDEX IF NOT EXISTS users_email_lower_unique ON users (LOWER(email));
ALTER TABLE users ADD COLUMN IF NOT EXISTS total_character_voiced_turns INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS total_interactive_canvas_used INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS age_attested_at TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS age_attestation_version TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS banned_at TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS ban_reason TEXT;

-- Evidence and reports survive account or theater deletion. IDs deliberately
-- retain the original identity even when the corresponding account is removed.
CREATE TABLE IF NOT EXISTS theater_report_snapshots (
    snapshot_id TEXT PRIMARY KEY,
    theater_id TEXT NOT NULL,
    content_sha256 TEXT NOT NULL,
    storage_path TEXT NOT NULL,
    created_at TEXT NOT NULL,
    UNIQUE (theater_id, content_sha256)
);
CREATE TABLE IF NOT EXISTS theater_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    theater_id TEXT NOT NULL,
    theater_name TEXT NOT NULL,
    owner_user_id BIGINT NOT NULL,
    active_orator_user_id BIGINT NOT NULL,
    reporter_user_id BIGINT NOT NULL,
    reason TEXT NOT NULL,
    details TEXT NOT NULL,
    snapshot_id TEXT NOT NULL REFERENCES theater_report_snapshots(snapshot_id),
    created_at TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'reviewed', 'dismissed', 'actioned')),
    reviewed_at TEXT,
    reviewer_user_id BIGINT,
    review_notes TEXT NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS theater_reports_review_idx ON theater_reports(status, created_at);
CREATE INDEX IF NOT EXISTS theater_reports_owner_idx ON theater_reports(owner_user_id, created_at);
CREATE INDEX IF NOT EXISTS theater_reports_orator_idx ON theater_reports(active_orator_user_id, created_at);
CREATE INDEX IF NOT EXISTS theater_reports_reporter_idx ON theater_reports(reporter_user_id, created_at);

CREATE TABLE IF NOT EXISTS user_feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_user_id BIGINT NOT NULL,
    category TEXT NOT NULL CHECK (category IN ('bug', 'suggestion')),
    details TEXT NOT NULL,
    theater_id TEXT,
    created_at TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'reviewed', 'dismissed', 'actioned')),
    reviewed_at TEXT,
    reviewer_user_id BIGINT,
    review_notes TEXT NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS user_feedback_review_idx ON user_feedback(category, status, created_at);
CREATE INDEX IF NOT EXISTS user_feedback_reporter_idx ON user_feedback(reporter_user_id, created_at);

CREATE TABLE IF NOT EXISTS auth_sessions (
    token TEXT PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TEXT NOT NULL,
    expires_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS auth_sessions_user_id_idx ON auth_sessions(user_id);
CREATE INDEX IF NOT EXISTS auth_sessions_expires_at_idx ON auth_sessions(expires_at);

CREATE TABLE IF NOT EXISTS theaters (
    theater_id TEXT PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    name TEXT,
    join_key TEXT,
    cost DOUBLE PRECISION NOT NULL DEFAULT 5.0,
    created_at TEXT,
    contributors TEXT NOT NULL DEFAULT '[]',
    active_orator_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    baton_request TEXT,
    is_persistent BOOLEAN NOT NULL DEFAULT FALSE,
    last_billed_at TEXT,
    exported_at TEXT
);
CREATE INDEX IF NOT EXISTS theaters_user_id_idx ON theaters(user_id);
CREATE INDEX IF NOT EXISTS theaters_join_key_upper_idx ON theaters(UPPER(join_key));


CREATE TABLE IF NOT EXISTS theater_views (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    theater_id TEXT NOT NULL,
    user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    viewed_at TEXT NOT NULL,
    ip_address TEXT
);
CREATE INDEX IF NOT EXISTS theater_views_theater_viewed_at_idx ON theater_views(theater_id, viewed_at DESC);
CREATE INDEX IF NOT EXISTS theater_views_viewed_at_idx ON theater_views(viewed_at);

CREATE TABLE IF NOT EXISTS payment_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    amount_usd DOUBLE PRECISION NOT NULL,
    credits_added DOUBLE PRECISION NOT NULL,
    payment_method TEXT NOT NULL,
    status TEXT NOT NULL,
    created_at TEXT NOT NULL,
    stripe_session_id TEXT
);
CREATE INDEX IF NOT EXISTS payment_transactions_user_id_idx ON payment_transactions(user_id, id DESC);
CREATE UNIQUE INDEX IF NOT EXISTS payment_transactions_stripe_session_unique
    ON payment_transactions(stripe_session_id) WHERE stripe_session_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS usage_events (
    idempotency_key TEXT PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    voice_minutes DOUBLE PRECISION NOT NULL,
    images_created INTEGER NOT NULL,
    music_created INTEGER NOT NULL DEFAULT 0,
    story_plans INTEGER NOT NULL DEFAULT 0,
    character_voiced_turns INTEGER NOT NULL DEFAULT 0,
    interactive_canvas_used INTEGER NOT NULL DEFAULT 0,
    layered_animations_created INTEGER NOT NULL DEFAULT 0,
    credit_cost DOUBLE PRECISION NOT NULL,
    created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS usage_events_user_id_idx ON usage_events(user_id);
ALTER TABLE usage_events ADD COLUMN IF NOT EXISTS character_voiced_turns INTEGER NOT NULL DEFAULT 0;
ALTER TABLE usage_events ADD COLUMN IF NOT EXISTS interactive_canvas_used INTEGER NOT NULL DEFAULT 0;
ALTER TABLE usage_events ADD COLUMN IF NOT EXISTS layered_animations_created INTEGER NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS password_reset_tokens (
    token TEXT PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TEXT NOT NULL,
    expires_at TEXT NOT NULL,
    used BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE INDEX IF NOT EXISTS password_reset_tokens_user_id_idx ON password_reset_tokens(user_id);
CREATE INDEX IF NOT EXISTS password_reset_tokens_expires_at_idx ON password_reset_tokens(expires_at);

CREATE TABLE IF NOT EXISTS credit_referrals (
    token TEXT PRIMARY KEY,
    sender_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    credits DOUBLE PRECISION NOT NULL CHECK (credits > 0),
    created_at TEXT NOT NULL,
    expires_at TEXT NOT NULL,
    claimed_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    claimed_at TEXT,
    status TEXT NOT NULL DEFAULT 'pending'
);
CREATE INDEX IF NOT EXISTS credit_referrals_sender_created_idx
    ON credit_referrals(sender_user_id, created_at DESC);

-- Private music-catalog search index. Audio stays in private artifact storage;
-- this schema stores only descriptions and the corpus statistics needed for BM25.
CREATE TABLE IF NOT EXISTS music_catalog_tracks (
    id TEXT PRIMARY KEY,
    artifact_filename TEXT NOT NULL UNIQUE,
    prompt TEXT NOT NULL,
    provider TEXT NOT NULL,
    model TEXT NOT NULL,
    token_count INTEGER NOT NULL,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS music_catalog_terms (
    track_id TEXT NOT NULL REFERENCES music_catalog_tracks(id) ON DELETE CASCADE,
    term TEXT NOT NULL,
    term_frequency INTEGER NOT NULL,
    PRIMARY KEY (track_id, term)
);
CREATE INDEX IF NOT EXISTS music_catalog_terms_term_track_idx ON music_catalog_terms(term, track_id);

CREATE TABLE IF NOT EXISTS music_catalog_term_stats (
    term TEXT PRIMARY KEY,
    document_frequency INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS music_catalog_stats (
    id BOOLEAN PRIMARY KEY DEFAULT TRUE CHECK (id),
    document_count INTEGER NOT NULL DEFAULT 0,
    total_token_count BIGINT NOT NULL DEFAULT 0
);
INSERT INTO music_catalog_stats (id) VALUES (TRUE) ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS user_stamps (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    filename TEXT NOT NULL,
    content_type TEXT NOT NULL DEFAULT 'image/png',
    created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS user_stamps_user_id_idx ON user_stamps(user_id);
