"""Create a PostgreSQL SQL dump from a valid Narratron SQLite database.

The generated file is self-contained: it creates the PostgreSQL schema, imports
all application rows in foreign-key order, and resets identity sequences. It
does not connect to Cloud SQL.
"""

import argparse
import sqlite3
from pathlib import Path


TABLES = (
    "users",
    "auth_sessions",
    "canvas_deployments",
    "exported_theaters",
    "theater_views",
    "payment_transactions",
    "usage_events",
    "password_reset_tokens",
)
BOOLEAN_COLUMNS = {
    ("users", "stats_visible"),
    ("canvas_deployments", "is_persistent"),
    ("password_reset_tokens", "used"),
}
IDENTITY_TABLES = ("users", "theater_views", "payment_transactions")


def sql_value(value, is_boolean: bool = False) -> str:
    """Return a safely quoted PostgreSQL literal for a SQLite cell."""
    if value is None:
        return "NULL"
    if is_boolean:
        return "TRUE" if bool(value) else "FALSE"
    if isinstance(value, bytes):
        return "decode('" + value.hex() + "', 'hex')"
    if isinstance(value, (int, float)):
        return str(value)
    return "'" + str(value).replace("'", "''") + "'"


def dump(source: Path, output: Path) -> None:
    if not source.is_file():
        raise FileNotFoundError(f"SQLite source database not found: {source}")
    source_conn = sqlite3.connect(f"file:{source}?mode=ro", uri=True)
    source_conn.row_factory = sqlite3.Row
    try:
        integrity = source_conn.execute("PRAGMA integrity_check").fetchone()[0]
        if integrity != "ok":
            raise RuntimeError(f"SQLite integrity check failed: {integrity}")

        available = {
            row[0]
            for row in source_conn.execute(
                "SELECT name FROM sqlite_master WHERE type = 'table' AND name NOT LIKE 'sqlite_%'"
            )
        }
        missing = set(TABLES) - available
        if missing:
            raise RuntimeError(f"SQLite database is missing expected tables: {', '.join(sorted(missing))}")

        schema = (Path(__file__).parents[1] / "storage" / "schema" / "postgres.sql").read_text(encoding="utf-8")
        with output.open("w", encoding="utf-8", newline="\n") as target:
            target.write("-- Generated by scripts/sqlite_to_postgres_sql.py.\nBEGIN;\n\n")
            target.write(schema)
            target.write("\n\n")
            for table in TABLES:
                rows = source_conn.execute(f"SELECT * FROM {table}").fetchall()
                target.write(f"-- {table}: {len(rows)} rows\n")
                for row in rows:
                    columns = list(row.keys())
                    values = ", ".join(
                        sql_value(row[column], (table, column) in BOOLEAN_COLUMNS)
                        for column in columns
                    )
                    target.write(
                        f"INSERT INTO {table} ({', '.join(columns)}) VALUES ({values}) ON CONFLICT DO NOTHING;\n"
                    )
                target.write("\n")

            for table in IDENTITY_TABLES:
                target.write(
                    "SELECT setval(pg_get_serial_sequence('"
                    + table
                    + "', 'id'), COALESCE((SELECT MAX(id) FROM "
                    + table
                    + "), 1), true);\n"
                )
            target.write("\nCOMMIT;\n")
    finally:
        source_conn.close()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", type=Path, help="Valid source SQLite .db file")
    parser.add_argument("--output", type=Path, required=True, help="PostgreSQL .sql file to create")
    args = parser.parse_args()
    dump(args.source, args.output)
    print(f"Created {args.output}")
